### ISSUE TITLE
_mintSingle function visibility.

### ISSUE THREAD

**Issue by uranium93** [DonkeVerse/ERC1155D#1]
`_mintSingle` is exposed as `external` and I believe this should be restricted to internal because : 

- This can lead to unexpected behaviors if used by others without being aware that the function can mint tokens
- The contract should be flexible in a way to use the core implementation without the need to delete undesirable behaviours
- The function is not part of ERC1155

PS: Thanks for sharing this implementation.

**Comment by DonkeVerse** [comment]
Excellent point! This was external to make gas testing easy, but this should be changed.

**Comment by DonkeVerse** [comment]
Changed with https://github.com/DonkeVerse/ERC1155D/commit/7b71fb3d3e1e9b0f34e32547240ca2fd886f4f50
